source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

#pod 'UITextField-Shake-Swift', :git => 'https://github.com/King-Wizard/UITextfield-Shake-Swift', :branch => 'master'
pod 'UITextField-Shake-Swift', :path => '../'
